### ISSUE TITLE
Handle Var unit code '00'  in CTL vars section 

### ISSUE THREAD

**Issue by wasdal** [miniufo/xgrads#19]
Some users use to set '00' instead of '0' when describing a variable in VARS section of CTL. Example:

`rain 1 00 rain analysis`

xgrads produces this error for that case: _invalid storage 00, only "99" or "-1,20" are supported_

In line 413 of io.py module the comparison is made: `elif var.storage == '99' or var.storage == '0':`

**Comment by miniufo** [comment]
Hi, thanks.  Although the description at [here](http://cola.gmu.edu/grads/gadoc/descriptorfile.html#VARS) (see the `unit` section) does not mention the case, I tried with '00', '000', '11' ...  It seems that they all work in GrADS.

However, this is really complicated since the `unit` section has many possible choices.  Without a clear definition, I can only add some possibilities here like:
`elif var.storage in ['99', '0', '00', '000', '1', '11', '111']`

Hope this helps.

**Comment by wasdal** [comment]
Yes. I also think there is no simple/single condition to test, just enumerating values. By now including '00' and the like in the list will help.

Thanks !

**Comment by miniufo** [comment]
Glad it helps.  Don't forget to star it if you like it.  Thanks very much.
